use std::error::Error;

#[tokio::test]
async fn test_loopix() -> Result<(), Box<dyn Error>>{

    Ok(())
}